name: enhanced_mobs
version: '${project.version}'
main: cn.yanshiqwq.enhanced_mobs.Main
api-version: 1.19
commands:
  spawnmob:
    usage: /<command> [test function]
    permission: <plugin name>.spawnmob
    permission-message: You don't have <permission>
  randomitem:
    usage: /<command> [test function]
    permission: <plugin name>.randomitem
    permission-message: You don't have <permission>
permissions:
  spawnmob:
    default: op
  randomitem:
    default: op