name: enhanced_mobs
version: '${project.version}'
main: cn.yanshiqwq.enhanced_mobs.Main
api-version: 1.19
commands:
  test:
    description: This is a demo command.
    usage: /<command> [test function]
    permission: <plugin name>.test
    permission-message: You don't have <permission>
permissions:
  test.*:
    children:
      test.strength: true
      test.enhance: true
  test.strength:
    default: op
  test.enhance:
    default: op